server:
  port: 8080
spring:
  application:
    name: 'autentication'
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: '/h2'

  flyway:
    enabled: true
    # Flyway usará su propio DataSource JDBC si se provee esta URL
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE_AUTENTICATION:autentication}'
    user: '${MYSQL_USER:root}'
    password: '${MYSQL_PASSWORD:root}'
    locations: 'classpath:db/migration'
    connect-retries: 3
    placeholders:
      db: '${adapters.r2dbc.database}'

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true

r2dbc:
  url: 'r2dbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}'
  username: '${adapters.r2dbc.username}'
  password: '${adapters.r2dbc.password}'
  pool:
    initial-size: 5
    max-size: 20
    max-idle-time: 30m

adapters:
  r2dbc:
    host: '${MYSQL_HOST:localhost}'
    port: '${MYSQL_PORT:3306}'
    database: '${MYSQL_DATABASE_AUTENTICATION:autentication}'
    username: '${MYSQL_USER:root}'
    password: '${MYSQL_PASSWORD:root}'

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
      base-path: '/actuator'
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
cors:
  allowed-origins: '*'

# JWT Configuration
security:
  jwt:
    # CADENA ALEATORIA DE >= 32 BYTES
    secret: ${JWT_KEY_SECRET:fQZJCefphgnEAnD9WlLBIQbpzV351d0mb3oGGsT6bvtaSqIZbTSId6wDwV3B1CbxEO7JlxQK6obNR9oUjDlYGg==}
    ttl-minutes: 60

# App Configuration
app:
  issuer: '${JWT_ISSUER:PowerUp}'
  audience: 'PowerUp-API'
  publicPaths: /h2/**,/api/v1/login,/api/v1/health,/api/v1/ping,/api/v1/test,/actuator/**,/v3/api-docs/**,/v3/api-docs/swagger-config,/swagger-ui.html,/swagger-ui/**,/webjars/**
