server:
  port: 8080
spring:
  application:
    name: "autentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

  flyway:
    enabled: true
    # Flyway usará su propio DataSource JDBC si se provee esta URL
    url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}"
    user: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"
    locations: "classpath:db/migration"
    connect-retries: 3
    placeholders:
      db: "${adapters.r2dbc.database}"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

r2dbc:
  url: "r2dbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}"
  username: "${adapters.r2dbc.username}"
  password: "${adapters.r2dbc.password}"
  pool:
    initial-size: 5
    max-size: 20
    max-idle-time: 30m


adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "autentication"
    username: "root"
    password: "andres98"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

# JWT Configuration
jwt:
  secret: "yJ3rjUq8TpwA7mSz8pQ4n0uFhUnX0cUj5jC0hvQz07w"
  expiration: 86400000  # 24 horas

# App Configuration
app:
  issuer: "PowerUp"
  audience: "PowerUp-API"



